---
- hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - debug:
       msg: "{{ survery_vlan_name }}" 
    - name: Gather only the config and default facts
      cisco.ios.ios_facts:
        gather_subset:
          - config         
