---
- hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Gather only the config and default facts
      cisco.ios.ios_facts:
        gather_subset:
          - config         
      register: show_run
    - debug:
        msg: '{{ show_run }}'
