---
- hosts: staging_switches
  connection: network_cli
  gather_facts: no
  tasks:
   - name: Create Vlan on staging swtiches
     cisco.ios.ios_vlans:
       config:
         - name: "{{ userid }}_{{ project_name }}_{{ vlan_id }}"
           vlan_id: "{{ vlan_id }}"
           state: active
